# Generated by Django 5.0.6 on 2024-06-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetvalue',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
