# Generated by Django 5.0.6 on 2024-06-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_dataset_id_alter_datasetvalue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetvalue',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
