# Generated by Django 5.0.6 on 2024-06-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_dataset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetvalue',
            name='country',
            field=models.CharField(default=2, max_length=16),
            preserve_default=False,
        ),
    ]
